# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker container prune -f
  - docker image prune -f
  - docker login -u "pheonix991" -p "$DOCKER_PASSWORD"

build-master:
  stage: build
  script:
    - docker build -t "pheonix991/$CI_PROJECT_NAME:latest" .
    - docker push "pheonix991/$CI_PROJECT_NAME:latest"
  only:
    - master
  tags:
    - dockerbuild

build:
  stage: build
  script:
    - docker build --pull -t "pheonix991/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME" .
    - docker push "pheonix991/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"
  except:
    - master
  tags:
    - dockerbuild